services:
  app:
    image: gautam112/newsapi112:latest
    ports:
      - "5001:5001"
    depends_on:
      - mysql

  mysql:
      image: gautam112/newsapi112:1.0
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: sentiment_analysis
      ports:
        - "3306:3306"