name: Publish Docker Images

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      
      # -
      #   name: Setting Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - 
        name: Build and push News API Image
        uses: docker/build-push-action@v4
        with:
          # context: .
          push: true
          tags: |
            gautam112/news-api-final-app:latest
            gautam112/news-api-final-mysql:latest

        
      # - 
      #   name: Build and push Mysql Image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: mysql/
      #     push: true
      #     tags: gautam112/newsapi112:latest